name: "publish"

on:
  push:
    branches: ["*"]

jobs:
  check-version:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check-tag.outputs.should_release }}
      version: ${{ steps.get-version.outputs.version }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version from package.json
        id: get-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check-tag
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          if git ls-remote --tags origin | grep -q "refs/tags/v${VERSION}$"; then
            echo "该版本 v${VERSION} 已发布"
            echo "should_release=false" >> $GITHUB_OUTPUT
          else
            echo "版本 v${VERSION} 未发布，继续构建"
            echo "should_release=true" >> $GITHUB_OUTPUT
          fi

  create-release:
    needs: check-version
    if: needs.check-version.outputs.should_release == 'true'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v4

      - name: create release
        id: create-release
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${{ needs.check-version.outputs.version }}`,
              name: `Desktop App v${{ needs.check-version.outputs.version }}`,
              body: 'Take a look at the assets to download and install this app.',
              draft: true,
              prerelease: false
            })
            return data.id

  build-tauri:
    needs: [check-version, create-release]
    if: needs.check-version.outputs.should_release == 'true'
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # 用于 ARM 架构的 Mac（M1及以上）
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # 用于 Intel 架构的 Mac
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04" # 用于 Linux 系统
            args: ""
          - platform: "windows-latest" # 用于 Windows x64 系统
            args: ""
          - platform: "windows-latest" # 用于 Windows ARM64 系统
            args: "--target aarch64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Download logo file
        run: |
          mkdir -p src-tauri/icons
          curl -L https://raw.githubusercontent.com/kuaifan/dootask/pro/public/images/logo-app.icns -o src-tauri/icons/icon.icns
          curl -L https://raw.githubusercontent.com/kuaifan/dootask/pro/public/images/logo-app.ico -o src-tauri/icons/icon.ico
          curl -L https://raw.githubusercontent.com/kuaifan/dootask/pro/public/images/logo-app.png -o src-tauri/icons/icon.png

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || matrix.platform == 'windows-latest' && contains(matrix.args, 'aarch64') && 'aarch64-pc-windows-msvc' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 用于 Tauri v1，webkitgtk 4.1 用于 Tauri v2
        # 如果确定使用的 Tauri 版本，可以删除不需要的依赖来加快工作流程

      - name: install frontend dependencies
        run: yarn install # 可以根据项目使用的包管理器改为 npm、pnpm 或 bun

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          args: ${{ matrix.args }}

      - name: Upload binary artifacts (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          cd src-tauri/target/release
          # 显示目录内容以检查实际文件名
          ls -la
          # 使用 package.json 中的 name 字段值
          zip -j linux-x86_64.zip dootask-server
          gh release upload "v${{ needs.check-version.outputs.version }}" linux-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary artifacts (Windows)
        if: matrix.platform == 'windows-latest' && !contains(matrix.args, 'aarch64')
        run: |
          cd src-tauri/target/release
          7z a windows-x86_64.zip dootask.exe
          gh release upload "v${{ needs.check-version.outputs.version }}" windows-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary artifacts (Windows ARM)
        if: matrix.platform == 'windows-latest' && contains(matrix.args, 'aarch64')
        run: |
          cd src-tauri/target/aarch64-pc-windows-msvc/release
          7z a windows-arm64.zip dootask.exe
          gh release upload "v${{ needs.check-version.outputs.version }}" windows-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary artifacts (macOS Intel)
        if: matrix.platform == 'macos-latest' && contains(matrix.args, 'x86_64')
        run: |
          cd src-tauri/target/x86_64-apple-darwin/release
          ls -la
          zip -j macos-x86_64.zip dootask-server
          gh release upload "v${{ needs.check-version.outputs.version }}" macos-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary artifacts (macOS ARM)
        if: matrix.platform == 'macos-latest' && contains(matrix.args, 'aarch64')
        run: |
          cd src-tauri/target/aarch64-apple-darwin/release
          ls -la
          zip -j macos-arm64.zip dootask-server
          gh release upload "v${{ needs.check-version.outputs.version }}" macos-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    needs: [check-version, create-release, build-tauri]
    if: needs.check-version.outputs.should_release == 'true'
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v7
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
